name: asio_soundboard

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  web_socket_channel: 2.1.0
  flutter_native_splash: 2.1.3+1
  quiver: 3.0.1+1
  http: 0.13.4
  shared_preferences: 2.0.13
  system_theme: 2.0.0
  flex_color_picker: 2.3.1
  easy_localization: 3.0.0

dev_dependencies:
  flutter_lints: 1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
flutter_native_splash:
  color: "#333333"
  image: assets/splash/logo_flutter_1080px_clr.png