name: asio_soundboard

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  web_socket_channel:
  flutter_native_splash:
  quiver:

dev_dependencies:
  flutter_lints:

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#333333"
  image: assets/splash/logo_flutter_1080px_clr.png