name: Main workflow

on: 
  push:
    branches:
      # - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - name: Configure Git
        run: git config --global url."https://".insteadOf git://
      - name: Configure Flutter
        run: flutter --version
      - name: Get dependencies
        run: flutter pub get
        working-directory: flutter-ui
      # - run: powershell -Command "(gc D:\a\hk_launcher\hk_launcher\windows\flutter\ephemeral\.plugin_symlinks\system_theme\windows\system_theme_plugin.cpp) -replace 'GetDarkModeEnabled', 'GetAppDarkModeEnabled' | Out-File D:\a\hk_launcher\hk_launcher\windows\flutter\ephemeral\.plugin_symlinks\system_theme\windows\system_theme_plugin.cpp"
      - name: Build UI
        run: flutter build windows
        working-directory: flutter-ui
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Build Host
        run: dotnet build ASIOSoundboard
      - name: Assemble final app
        run: powershell Copy-Item -Path "flutter-ui\build\windows\runner\Release" -Destination "ASIOSoundboard\bin\Release\net6.0-windows\flutter-ui" -Recurse
        run: powershell Copy-Item -Path "ahk" -Destination "ASIOSoundboard\bin\Release\net6.0-windows\ahk" -Recurse
      - uses: actions/upload-artifact@v3
        with:
          name: ASIOSoundboard
          path: ASIOSoundboard\bin\Release\net6.0-windows
